/**
 * SkillPanel — slide-in panel for viewing and editing the EDA skill file.
 *
 * The skill file (skill.md) is generated by the EDA agent and contains:
 *   - Acronym Mappings: abbreviations → full expansions used in NLP search
 *   - Notes: free-form domain notes
 *
 * Users can add/delete/edit acronym rows, edit notes, and save back to the
 * backend via PUT /eda/skill. Re-inference can be triggered via POST /eda/refresh,
 * which shows a live EDAProgress checklist fed by GET /eda/events SSE.
 */

import { useEffect, useRef, useState } from "react";
import { useTranslation } from "react-i18next";
import EDAProgress from "./EDAProgress";

// ---------------------------------------------------------------------------
// Skill file serialiser — mirrors the backend format
// ---------------------------------------------------------------------------

function buildSkillContent(acronyms, notes) {
  const seen = new Set();
  const rows = acronyms
    .map((r) => ({
      acronym: r.acronym.trim().toUpperCase(),
      expansion: r.expansion.trim(),
    }))
    .filter((r) => r.acronym && r.expansion)
    .filter((r) => {
      const key = `${r.acronym.toLowerCase()}::${r.expansion.toLowerCase()}`;
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    })
    .sort((a, b) =>
      a.acronym.localeCompare(b.acronym) || a.expansion.localeCompare(b.expansion)
    )
    .map((r) => `| ${r.acronym} | ${r.expansion} |`)
    .join("\n");

  const tableSection = rows || "| (none found yet) | — |";
  const notesSection =
    notes.trim() ||
    "<!-- Add domain notes here. This section is never overwritten. -->";

  return `# QQL Skill File
> Auto-generated by the EDA agent. Edit freely — your changes are preserved across re-generations.

## Acronym Mappings
Abbreviations recognized in user queries and expanded for product search.

| Acronym | Expansion |
|---------|-----------|
${tableSection}

## Notes
${notesSection}
`;
}

// ---------------------------------------------------------------------------
// Sub-components
// ---------------------------------------------------------------------------

function AcronymRow({ row, index, onChange, onDelete }) {
  const { t } = useTranslation();
  return (
    <tr className="border-t border-gray-800 group">
      <td className="py-1.5 pr-2">
        <input
          className="w-full bg-transparent text-gray-200 text-sm font-mono
                     border border-transparent hover:border-gray-700 focus:border-indigo-500
                     rounded px-1.5 py-0.5 outline-none transition-colors"
          value={row.acronym}
          onChange={(e) => onChange(index, "acronym", e.target.value)}
          placeholder={t("skill.newAcronymPlaceholder")}
        />
      </td>
      <td className="py-1.5 pr-2">
        <input
          className="w-full bg-transparent text-gray-300 text-sm
                     border border-transparent hover:border-gray-700 focus:border-indigo-500
                     rounded px-1.5 py-0.5 outline-none transition-colors"
          value={row.expansion}
          onChange={(e) => onChange(index, "expansion", e.target.value)}
          placeholder={t("skill.newExpansionPlaceholder")}
        />
      </td>
      <td className="py-1.5 w-6 text-right">
        <button
          onClick={() => onDelete(index)}
          className="opacity-0 group-hover:opacity-100 text-gray-600 hover:text-red-400
                     transition-opacity text-xs leading-none"
          title="Delete row"
        >
          ✕
        </button>
      </td>
    </tr>
  );
}

// ---------------------------------------------------------------------------
// Main panel
// ---------------------------------------------------------------------------

export default function SkillPanel({ onClose }) {
  const { t } = useTranslation();
  const panelRef = useRef(null);

  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [reinferring, setReinferring] = useState(false);
  const [saveFlash, setSaveFlash] = useState(false);
  const [error, setError] = useState(null);

  const [acronyms, setAcronyms] = useState([]); // [{acronym, expansion}]
  const [notes, setNotes] = useState("");
  const [search, setSearch] = useState("");

  // ── Data fetching ──────────────────────────────────────────────────────

  const fetchSkill = async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/eda/skill");
      if (!res.ok) throw new Error(t("skill.errorLoad"));
      const data = await res.json();
      setAcronyms(data.acronyms || []);
      setNotes(data.notes || "");
    } catch (e) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchSkill();
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  // Close on Escape key
  useEffect(() => {
    const handler = (e) => e.key === "Escape" && onClose();
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, [onClose]);

  // ── Acronym table actions ──────────────────────────────────────────────

  const handleChange = (index, field, value) => {
    setAcronyms((prev) =>
      prev.map((row, i) => (i === index ? { ...row, [field]: value } : row))
    );
  };

  const handleDelete = (index) => {
    setAcronyms((prev) => prev.filter((_, i) => i !== index));
  };

  const handleAddRow = () => {
    setAcronyms((prev) => [...prev, { acronym: "", expansion: "" }]);
  };

  // ── Save & re-infer ────────────────────────────────────────────────────

  const handleSave = async () => {
    setSaving(true);
    setError(null);
    try {
      const content = buildSkillContent(acronyms, notes);
      const res = await fetch("/eda/skill", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ content }),
      });
      if (!res.ok) throw new Error(t("skill.errorSave"));
      setSaveFlash(true);
      setTimeout(() => setSaveFlash(false), 2000);
      await fetchSkill(); // reload to normalise content
    } catch (e) {
      setError(e.message);
    } finally {
      setSaving(false);
    }
  };

  const handleReinfer = async () => {
    setReinferring(true);
    setError(null);

    // Fire the refresh — it blocks until the full EDA run finishes.
    // EDAProgress handles live feedback independently via SSE.
    try {
      const res = await fetch("/eda/refresh", { method: "POST" });
      if (!res.ok) {
        const body = await res.json().catch(() => null);
        throw new Error(body?.detail || t("skill.reinferError"));
      }
    } catch (e) {
      // When the skill file is empty (first run) don't show a scary error —
      // the empty-state card already tells users what to do.
      if (acronyms.length > 0) {
        setError(e.message);
      }
      setReinferring(false);
    }
    // Don't setReinferring(false) on success here — EDAProgress.onDone handles it.
  };

  // Called by EDAProgress when the "done" SSE event arrives.
  const handleReinferDone = async () => {
    await fetchSkill(); // reload the updated acronym table
    setReinferring(false);
  };

  // ── Render ─────────────────────────────────────────────────────────────

  return (
    <>
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-black/40 z-40"
        onClick={onClose}
        aria-hidden="true"
      />

      {/* Panel */}
      <aside
        ref={panelRef}
        className="fixed right-0 top-0 h-full w-full max-w-md bg-gray-900 border-l border-gray-800
                   z-50 flex flex-col shadow-2xl"
        role="dialog"
        aria-label={t("skill.title")}
      >
        {/* Header */}
        <div className="flex items-start justify-between px-5 py-4 border-b border-gray-800 flex-shrink-0">
          <div>
            <h2 className="text-base font-semibold text-gray-100 flex items-center gap-2">
              <span>🧠</span>
              {t("skill.title")}
            </h2>
            <p className="text-xs text-gray-500 mt-0.5">{t("skill.subtitle")}</p>
          </div>
          <button
            onClick={onClose}
            className="text-gray-500 hover:text-gray-300 transition-colors text-lg leading-none ml-4 mt-0.5"
            aria-label="Close"
          >
            ✕
          </button>
        </div>

        {/* Body */}
        <div className="flex-1 overflow-y-auto px-5 py-4 space-y-6">
          {loading ? (
            <div className="text-gray-500 text-sm animate-pulse py-8 text-center">
              Loading…
            </div>
          ) : (
            <>
              {/* Acronym Mappings */}
              <section>
                <div className="mb-2">
                  <h3 className="text-sm font-medium text-gray-300">
                    {t("skill.acronymsTitle")}
                  </h3>
                  <p className="text-xs text-gray-600 mt-0.5">
                    {t("skill.acronymsHint")}
                  </p>
                </div>

                {acronyms.length === 0 ? (
                  <div className="rounded-lg border border-dashed border-gray-700
                                  px-4 py-5 text-center space-y-3 mt-1">
                    <p className="text-sm text-gray-400">{t("skill.empty")}</p>
                    <p className="text-xs text-gray-600 leading-relaxed">
                      {t("skill.emptyHint")}
                    </p>
                    <button
                      onClick={onClose}
                      className="text-xs text-indigo-400 hover:text-indigo-300
                                 transition-colors underline-offset-2 hover:underline"
                    >
                      {t("skill.emptyAction")} →
                    </button>
                  </div>
                ) : (
                  <table className="w-full text-sm">
                    <thead>
                      <tr className="text-left text-xs text-gray-600 uppercase tracking-wide">
                        <th className="pb-1.5 font-medium w-24">
                          {t("skill.colAcronym")}
                        </th>
                        <th className="pb-1.5 font-medium">
                          {t("skill.colExpansion")}
                        </th>
                        <th className="pb-1.5 w-6" />
                      </tr>
                    </thead>
                    <tbody>
                      {acronyms
                        .map((row, index) => ({ ...row, index }))
                        .filter((row) => {
                          if (!search.trim()) return true;
                          const term = search.toLowerCase();
                          return (
                            row.acronym.toLowerCase().includes(term) ||
                            row.expansion.toLowerCase().includes(term)
                          );
                        })
                        .map((row) => (
                          <AcronymRow
                            key={row.index}
                            row={row}
                            index={row.index}
                            onChange={handleChange}
                            onDelete={handleDelete}
                          />
                        ))}
                    </tbody>
                  </table>
                )}

                {acronyms.length > 0 && (
                  <div className="mt-2">
                    <input
                      className="w-full bg-gray-800 border border-gray-700 rounded-lg
                                 text-xs text-gray-300 px-3 py-2 outline-none
                                 focus:border-indigo-500 transition-colors placeholder-gray-600"
                      placeholder={t("skill.searchPlaceholder")}
                      value={search}
                      onChange={(e) => setSearch(e.target.value)}
                    />
                    {search.trim() &&
                      acronyms.filter((row) =>
                        row.acronym.toLowerCase().includes(search.toLowerCase()) ||
                        row.expansion.toLowerCase().includes(search.toLowerCase())
                      ).length === 0 && (
                        <p className="text-xs text-gray-600 mt-2">
                          {t("skill.searchEmpty")}
                        </p>
                      )}
                  </div>
                )}

                <button
                  onClick={handleAddRow}
                  className="mt-2 text-xs text-indigo-400 hover:text-indigo-300 transition-colors"
                >
                  {t("skill.addRow")}
                </button>
              </section>

              {/* Notes */}
              <section>
                <h3 className="text-sm font-medium text-gray-300 mb-2">
                  {t("skill.notesTitle")}
                </h3>
                <textarea
                  className="w-full h-28 bg-gray-800 border border-gray-700 rounded-lg
                             text-sm text-gray-300 px-3 py-2 resize-none outline-none
                             focus:border-indigo-500 transition-colors placeholder-gray-600"
                  placeholder={t("skill.notesPlaceholder")}
                  value={notes}
                  onChange={(e) => setNotes(e.target.value)}
                />
              </section>

              {/* Error */}
              {error && (
                <p className="text-xs text-red-400 bg-red-950/40 border border-red-900/40
                              rounded px-3 py-2">
                  {error}
                </p>
              )}
            </>
          )}
        </div>

        {/* Footer actions */}
        <div className="flex-shrink-0 border-t border-gray-800">
          {/* Live EDA progress checklist while re-inferring */}
          {reinferring && (
            <div className="px-5 pt-3 pb-1">
              <p className="text-[11px] text-gray-600 uppercase tracking-wider mb-2">
                {t("skill.reinferring")}
              </p>
              <EDAProgress onDone={handleReinferDone} />
              <p className="text-xs text-gray-600 italic mt-2 mb-1">
                {t("skill.reinferHint")}
              </p>
            </div>
          )}

          <div className="flex items-center justify-between px-5 py-4 gap-3">
            <button
              onClick={handleReinfer}
              disabled={reinferring || loading}
              className="text-xs text-gray-400 hover:text-gray-200 disabled:opacity-40
                         transition-colors"
            >
              {reinferring ? t("skill.reinferring") : t("skill.reinfer")}
            </button>

            <button
              onClick={handleSave}
              disabled={saving || loading || reinferring}
              className={`text-sm px-4 py-1.5 rounded-lg font-medium transition-all
                          disabled:opacity-40
                          ${
                            saveFlash
                              ? "bg-emerald-700 text-emerald-100"
                              : "bg-indigo-600 hover:bg-indigo-500 text-white"
                          }`}
            >
              {saving
                ? t("skill.saving")
                : saveFlash
                ? t("skill.saveSuccess")
                : t("skill.save")}
            </button>
          </div>
        </div>
      </aside>
    </>
  );
}
