import sqlglot
import sqlglot.expressions as exp
from sqlglot import parse_one

# Tables that exist in the DB. The SQL Agent is only allowed to query these.
# Updated dynamically by the EDA agent after table discovery.
_known_tables: frozenset[str] = frozenset({"sales"})


def set_known_tables(tables: frozenset[str]) -> None:
    """Register discovered tables — called by the EDA agent after profiling."""
    global _known_tables
    _known_tables = tables


# AST node types that indicate write / schema-modification operations.
# Walking the full AST (not just the top node) catches DML buried in subqueries or CTEs.
_FORBIDDEN_TYPES = (
    exp.Insert,
    exp.Update,
    exp.Delete,
    exp.Drop,
    exp.Create,
    exp.AlterTable,
    exp.TruncateTable,
    exp.Command,
)


class SQLVerificationError(ValueError):
    """Raised when generated SQL fails safety or validity checks. Always retryable."""


class SQLVerifier:
    def __init__(self, allowed_tables: frozenset[str] | None = None) -> None:
        """
        *allowed_tables*: restrict queries to this set. Defaults to KNOWN_TABLES.
        Pass a subset when the user has selected specific tables in the onboarding.
        """
        self._allowed = allowed_tables if allowed_tables is not None else _known_tables

    def verify(self, sql: str) -> str:
        """
        Parse and validate SQL. Returns normalized SQL string on success.

        Checks (in order):
        1. SQL must be parseable by sqlglot with PostgreSQL dialect.
        2. Top-level statement must be SELECT.
        3. No forbidden operation types anywhere in the AST.
        4. All referenced table names must be in KNOWN_TABLES.

        Returns:
            Normalized SQL string (re-generated by sqlglot, consistent formatting).

        Raises:
            SQLVerificationError: with a descriptive message for LLM retry context.
        """
        sql = sql.strip().rstrip(";")
        if not sql:
            raise SQLVerificationError("Empty SQL statement.")

        # 1. Parse
        try:
            tree = parse_one(sql, dialect="postgres")
        except sqlglot.errors.ParseError as e:
            raise SQLVerificationError(f"SQL parse error: {e}") from e

        # 2. Must be SELECT at top level
        if not isinstance(tree, exp.Select):
            raise SQLVerificationError(
                f"Only SELECT statements are allowed. Received: {type(tree).__name__}."
            )

        # 3. No forbidden node types anywhere in the AST (catches DML in subqueries/CTEs)
        for node in tree.walk():
            if isinstance(node, _FORBIDDEN_TYPES):
                raise SQLVerificationError(
                    f"Forbidden operation detected in query: {type(node).__name__}. "
                    "Only read-only SELECT queries are permitted."
                )

        # 4. All table references must be in allowed tables
        for table_node in tree.find_all(exp.Table):
            name = table_node.name.lower()
            if name and name not in self._allowed:
                raise SQLVerificationError(
                    f"Unknown table: '{name}'. "
                    f"Available tables: {sorted(self._allowed)}."
                )

        return tree.sql(dialect="postgres")
