"""
Schema inspector — builds the schema string injected into LLM system prompts.

The string has two parts:
  1. Structural schema: column names and data types from information_schema.
  2. Data context: the contents of data_context.md (generated by the EDA agent),
     which includes column value distributions, statistics, and user annotations.

Both parts are cached after the first call.  Call invalidate_schema_cache() to
force a rebuild (e.g. after POST /eda/refresh).
"""

from pathlib import Path

from .connection import get_pool

_schema_cache: str | None = None


def invalidate_schema_cache() -> None:
    """Discard the cached schema so the next call rebuilds it."""
    global _schema_cache
    _schema_cache = None


async def get_schema_description() -> str:
    """
    Return a compact schema description for injection into system prompts.
    Cached after the first successful call.
    """
    global _schema_cache
    if _schema_cache is not None:
        return _schema_cache

    # ── 1. Structural schema from information_schema ──────────────────────
    pool = get_pool()
    async with pool.acquire() as conn:
        rows = await conn.fetch(
            """
            SELECT
                c.table_name,
                c.column_name,
                c.data_type,
                c.is_nullable
            FROM information_schema.columns c
            WHERE c.table_schema = 'public'
            ORDER BY c.table_name, c.ordinal_position
            """
        )

    lines: list[str] = []
    current_table: str | None = None
    for row in rows:
        if row["table_name"] != current_table:
            current_table = row["table_name"]
            lines.append(f"\nTable: {current_table}")
        nullable = "" if row["is_nullable"] == "YES" else " NOT NULL"
        lines.append(f"  - {row['column_name']} ({row['data_type']}{nullable})")

    structural = "\n".join(lines).strip()

    # ── 2. Data context from data_context.md ─────────────────────────────
    from config import settings  # noqa: PLC0415 — avoid circular import at module level

    context_path = Path(settings.eda_context_path)
    data_context = ""
    if context_path.exists() and context_path.stat().st_size > 0:
        data_context = "\n\n---\n\n" + context_path.read_text(encoding="utf-8").strip()

    _schema_cache = structural + data_context
    return _schema_cache
